apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tifarafa/udagram-frontend:0.1.16
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #    #memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     #memory: "1024Mi"
        #     cpu: "500m"  
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
